### ISSUE TITLE
Be Generic over Hits

### ISSUE THREAD

**Issue by KodrAus** [stephanbuys/elastic-responses#2]
What do you think about being generic over the `Hits` type, like `Hits<T: Serialize>`? That would mean that generic `T` would leak all the way up to the `Response`, but with a [type alias](https://doc.rust-lang.org/book/type-aliases.html) you could provide something like `type Response = ResponseOf<Value>`, or something.

That could be more efficient for parsing responses where all the hits have the same type (`Value` is pretty slow), but adds extra complexity.

**Comment by stephanbuys** [comment]
@KodrAus, sounds cool - can you give an example of how this might pan out (novice here, so not quite following 100%)

**Comment by KodrAus** [comment]
Sure! I'll put together a quick PR this evening to show you what I mean.
